name: 'Typesafe.js Action'
description: 'GitHub Action for Typesafe.js'
inputs:
  lerna: 
    description: 'Whether lerna is enabled'
    required: true
    default: true
  node-version:  # id of input
    descriotion: 'Version of node to use'
    required: true
    default: 16
  npm-client:
    description: 'The npm client to use'
    required: true
    default: 'yarn'
  task:
    description: 'The task to run'
    required: true
    default: 'compile'
runs:
  using: 'docker'
  entrypoint: node packages/action/lib/action.js
  image: 'Dockerfile'
  args: 
    - ${{ inputs.TASK }}